### ISSUE TITLE
Terminar de escrever o README

### ISSUE THREAD

**Issue by felpesm** [felpesm/port-scanner#3]
Faltam:
- Uma descrição do projeto
- Pré-requisitos (incluir Dockerfile, referido em #2)
- Instruções de instalação (incluir Dockerfile, referido em #2)

**Comment by linasdias** [comment]
Posso ajudar?

**Comment by felpesm** [comment]
Certamente, seria bem-vinda. Só não vai dar para falar sobre o Dockerfile, pois ainda não foi implementado como a #2 indica. Mas fique a vontade. :smile:

**Comment by linasdias** [comment]
Quais são os outros pré-requisitos além do Dockerfile?

**Comment by felpesm** [comment]
O único outro pré-requisito era o Python. Aqui tudo foi testado na versão 3.7.x, não sei se versões abaixo funcionarão corretamente.

**Comment by felpesm** [comment]
Issue concluída no commit ef32a28
